<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<!--<ItemGroup>
		<None Remove=".gitignore" />
	</ItemGroup>-->

	<!--<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>-->
	

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="FluentAvaloniaUI" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Base\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\Chameleon.CommunityToolkit\Chameleon.CT.Common\Chameleon.CT.Common.csproj" />
	  <ProjectReference Include="..\..\..\src\Chameleon.Common\Chameleon.Common.csproj" />
	  <ProjectReference Include="..\Chameleon.Avalonia.Common\Chameleon.Avalonia.Common.csproj" />
	</ItemGroup>
</Project>
