<Project>
  <PropertyGroup>
	<Version>2025.0.1.0</Version>
	<PublishAot>false</PublishAot>
	<PublishTrimmed>false</PublishTrimmed>
	<StripSymbols>false</StripSymbols>
	<Nullable>enable</Nullable>
	<AvaloniaVersion>11.2.2</AvaloniaVersion>
	<JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
  	<Optimize>true</Optimize>
  </PropertyGroup>
</Project>
