<Project>
  <PropertyGroup>
    <Version>2024.1.1.1</Version>
    <PublishAot>false</PublishAot>
    <PublishTrimmed>false</PublishTrimmed>
    <StripSymbols>false</StripSymbols>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <PropertyGroup>
    <AvaloniaVersion>11.1.0-beta1</AvaloniaVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="11.1.4" />
    <PackageVersion Include="Avalonia.Desktop" Version="11.1.4" />
    <PackageVersion Include="Avalonia.Svg" Version="11.1.0.1" />
    <PackageVersion Include="Avalonia.Svg.Skia" Version="11.1.0.1" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="11.1.4" />
    <PackageVersion Include="Avalonia.Xaml.Behaviors" Version="11.1.0.5" />
    <PackageVersion Include="DynamicData" Version="9.0.4" />
    <PackageVersion Include="FluentAvaloniaUI" Version="2.1.0" />
    <PackageVersion Include="CommunityToolkit.HighPerformance" Version="8.3.1" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.3.2" />
	<PackageVersion Include="Dotnet.Bundle" Version="0.9.13" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="9.0.0-preview.6.24327.7" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Common" Version="4.11.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.FileExtensions" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Configuration" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
    <PackageVersion Include="Microsoft.IdentityModel.LoggingExtensions" Version="8.1.2" />
  </ItemGroup>
</Project>