<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

   <PropertyGroup Label="Package Info">
   	<AssemblyVersion>2024.0.9.8</AssemblyVersion>
   </PropertyGroup>

  <ItemGroup>
    <Compile Remove="App\UserProfiles\Events\Sync\**" />
    <Compile Remove="App\UserProfiles\ViewModels\**" />
    <EmbeddedResource Remove="App\UserProfiles\Events\Sync\**" />
    <EmbeddedResource Remove="App\UserProfiles\ViewModels\**" />
    <None Remove="App\UserProfiles\Events\Sync\**" />
    <None Remove="App\UserProfiles\ViewModels\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="App\Bookmarks\Views\Details\" />
    <Folder Include="App\Settings\UserDefaultSettings\" />
    <Folder Include="ThirdParty\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\chameleon-lib\Chameleon.lib.Common\Chameleon.lib.Common.csproj" />
    <ProjectReference Include="..\..\Chameleon.Web\aspnet-core\src\Chameleon.Application.Shared\Chameleon.Application.Shared.csproj" />
  </ItemGroup>

</Project>
