<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
	  <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
	  <UseMaui>true</UseMaui>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Prism.Core" Version="9.0.271-pre" />
    <PackageReference Include="Prism.Maui" Version="9.0.271-pre" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.1" />
    <PackageReference Include="Unity" Version="5.11.10" />
	<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="App\Bookmarks\Views\Details\" />
    <Folder Include="App\UserProfiles\Events\Sync\" />
    <Folder Include="App\UserProfiles\ViewModels\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Chameleon.Web\aspnet-core\src\Chameleon.Application.Shared\Chameleon.Application.Shared.csproj" />
  </ItemGroup>
</Project>