<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="FluentAvaloniaUI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Chameleon.Core\Chameleon.Core.csproj" />
    <ProjectReference Include="..\..\..\src\Chameleon.Interfaces\Chameleon.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\PaginatorView.axaml" />
  </ItemGroup>

</Project>
