<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0</TargetFrameworks> 
	<Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
	<ApplicationIcon>logosymbol.ico</ApplicationIcon>
	<UseAppHost>true</UseAppHost>
	<AssemblyName>Chameleon</AssemblyName>
	   <!--<StartupObject>Chameleon.Av.Desktop.Program</StartupObject>
	  <OutputType>Exe</OutputType>-->
	  <!--<RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
	  <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>-->
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaXaml Remove="Properties\**" />
    <Compile Remove="Properties\**" />
    <EmbeddedResource Remove="Properties\**" />
    <None Remove="Properties\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="logosymbol.ico" />
  </ItemGroup>
	
  <ItemGroup>
	  <PackageReference Include="Avalonia" />
	  <PackageReference Include="Avalonia.Desktop" />
	  <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />
	  <PackageReference Include="Avalonia.Svg" />
	  <PackageReference Include="Avalonia.Svg.Skia" />
	  <PackageReference Include="Dotnet.Bundle" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\..\..\Chameleon.app.Avalonia\Chameleon.app.Avalonia.csproj" />
  </ItemGroup>
</Project>
