<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>	  
  </PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

  <ItemGroup>
	<PackageReference Include="Avalonia" />
	<PackageReference Include="Avalonia.Desktop" />
	<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />
	<PackageReference Include="Avalonia.Svg" />
	<PackageReference Include="Avalonia.Svg.Skia" />
	<PackageReference Include="FluentAvaloniaUI" />
	<PackageReference Include="DynamicData" />
	<PackageReference Include="CommunityToolkit.Mvvm" />
	<PackageReference Include="Mapster" />
	<PackageReference Include="ReactiveValidation.Avalonia" />
	<PackageReference Include="System.Configuration.ConfigurationManager" />
	<PackageReference Include="Microsoft.Playwright" />
	<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	<PackageReference Include="Microsoft.Extensions.Logging.Configuration" />
	<PackageReference Include="Microsoft.Extensions.Logging.Console" />
	<PackageReference Include="Microsoft.IdentityModel.LoggingExtensions" />
	<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
	<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
	<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
	<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\chameleon-lib\Chameleon.lib.Api\Chameleon.lib.Api.csproj" />
    <ProjectReference Include="..\..\chameleon-lib\Chameleon.lib.Common\Chameleon.lib.Common.csproj" />
    <ProjectReference Include="..\..\chameleon-lib\Chameleon.lib.Playwright\Chameleon.lib.Playwright.csproj" />
    <ProjectReference Include="..\..\chameleon-lib\Chameleon.lib.WebBrowser\Chameleon.lib.WebBrowser.csproj" />
    <ProjectReference Include="..\..\chameleon-lib\Chameleon.lib\Chameleon.lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\MboxLoginUserControl.axaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="Controls\MboxTitleUserControl.axaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="Features\ProfilesAndFolders\Search\ByTags\Controls\TagFolderSearchControl.axaml.cs">
      <DependentUpon>TagFolderSearchControl.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\PaginatorView.axaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="Views\PhoneVerificationView.axaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="Views\PlaywrightView.axaml.cs">
      <DependentUpon>PlaywrightView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ProxyCreditView.axaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="Views\UserDefaultSettingsView.axaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="Views\UserProxySettingsView.axaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
