<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net8.0-tizen</TargetFrameworks> -->
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="7.0.1" />
		<PackageReference Include="CommunityToolkit.Maui.Markup" Version="4.0.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.6" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.6" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\..\src\Chameleon.Core\Chameleon.Core.csproj" />
	  <ProjectReference Include="..\..\..\..\src\Chameleon.Interfaces\Chameleon.Interfaces.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Base\BaseGalleryPageResourceDictionary.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
