<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.Desktop" />
		<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />
		<PackageReference Include="FluentAvaloniaUI" />
		<PackageReference Include="Prism.Avalonia" />
		<PackageReference Include="Prism.DryIoc.Avalonia" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\src\Chameleon.Core\Chameleon.Core.csproj" />
	  <ProjectReference Include="..\..\..\src\Chameleon.Infrastructure\Chameleon.Infrastructure.csproj" />
	  <ProjectReference Include="..\Chameleon.Av.Fluent.Common\Chameleon.Av.Fluent.Common.csproj" />
	  <ProjectReference Include="..\Chameleon.Av.Fluent.Dialogs\Chameleon.Av.Fluent.Dialogs.csproj" />
	  <ProjectReference Include="..\Chameleon.Avalonia.Common\Chameleon.Avalonia.Common.csproj" />
	  <ProjectReference Include="..\Chameleon.Avalonia.Controls.Dashboard\Chameleon.Avalonia.Controls.Dashboard.csproj" />
	  <ProjectReference Include="..\Chameleon.Avalonia.Prism.Domain\Chameleon.Avalonia.Prism.Domain.csproj" />
	  <ProjectReference Include="..\Chameleon.Avalonia.Prism.Infrastructure\Chameleon.Avalonia.Prism.Infrastructure.csproj" />
	  <ProjectReference Include="..\Chameleon.Avalonia.Prism.Interfaces\Chameleon.Avalonia.Prism.Interfaces.csproj" />
	  <ProjectReference Include="..\Chameleon.Avalonia.Prism.Module.Auth\Chameleon.Avalonia.Prism.Module.Auth.csproj" />
	  <ProjectReference Include="..\Chameleon.Avalonia.Prism.Module\Chameleon.Avalonia.Prism.Module.csproj" />
	  <ProjectReference Include="..\Chameleon.Controls.Settings\Chameleon.Avalonia.Controls.Settings.csproj" />
	</ItemGroup>
</Project>
