<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" />
    <PackageReference Include="Polly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Chameleon.Infrastructure\Chameleon.Infrastructure.csproj" />
    <ProjectReference Include="..\Chameleon.Interfaces\Chameleon.Interfaces.csproj" />
  </ItemGroup>

</Project>
