<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Chameleon.Common\Chameleon.Common.csproj" />
    <ProjectReference Include="..\..\src\Chameleon.Core\Chameleon.Core.csproj" />
  </ItemGroup>

</Project>
