<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\chameleon-lib\Chameleon.lib.Common\Chameleon.lib.Common.csproj" />
    <ProjectReference Include="..\Chameleon.Interfaces\Chameleon.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exceptions\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
