<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
	  <PackageReference Include="Avalonia.Svg" />
	  <PackageReference Include="Avalonia.Svg.Skia" />
	  <PackageReference Include="FluentAvaloniaUI" />
	  <PackageReference Include="ReactiveValidation.Avalonia" />
	  <PackageReference Include="DynamicData" />
	  <PackageReference Include="CommunityToolkit.Mvvm" />

    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\chameleon-lib\Chameleon.assets\chameleon.assets.csproj" />
    <ProjectReference Include="..\..\chameleon-lib\Chameleon.lib\Chameleon.lib.csproj" />
    <ProjectReference Include="..\..\chameleon-lib\Chameleon.lib.AIR\Chameleon.lib.AIR.csproj" />
    <ProjectReference Include="..\..\chameleon-lib\Chameleon.lib.Api\Chameleon.lib.Api.csproj" />
    <ProjectReference Include="..\..\chameleon-lib\Chameleon.lib.Playwright\Chameleon.lib.Playwright.csproj" />
    <ProjectReference Include="..\..\chameleon-lib\Chameleon.lib.WebBrowser\Chameleon.lib.WebBrowser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Features/Projects/Profiles/UserProfile.axaml.cs">
      <DependentUpon>UserProfile.axaml</DependentUpon>
    </Compile>
    <Compile Update="Features/Projects/View.axaml.cs">
      <DependentUpon>View.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
