<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>


	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>
	
  <ItemGroup>
	  <PackageReference Include="Avalonia" />
	  <PackageReference Include="Avalonia.AvaloniaEdit" />
	  <PackageReference Include="AvaloniaEdit.TextMate" />
	  <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />
    <PackageReference Include="FluentAvaloniaUI" />
  </ItemGroup>
	
  <ItemGroup>
    <Folder Include="Assets\" />
  </ItemGroup>

</Project>
