using Chameleon.ThirdParty.Codesverify.Models;
using System.Net.Http;

namespace Chameleon.ThirdParty.Codesverify;

public class CodesVerifyAPI
{
    public string ApiKey { get; set; }
    public List<Country> Countries { get; } =
    [
        new("USA")
    ];
    public List<AppData> Apps { get; } =
    [
        new("2RedBeans", "0.50"),
        new("3fun", "0.50"),
        new("5miles", "0.50"),
        new("abra", "0.70"),
        new("accountpatrol", "0.70"),
        new("adidas", "0.50"),
        new("adwallet", "0.70"),
        new("affirm", "0.50"),
        new("airbnb", "0.50"),
        new("alibaba", "0.50"),
        new("all set", "0.70"),
        new("amasia", "0.70"),
        new("amazon", "0.50"),
        new("ankama", "0.70"),
        new("aol", "0.50"),
        new("apple", "0.50"),
        new("Arizona", "0.50"),
        new("atom", "0.50"),
        new("authy", "0.70"),
        new("AWS", "0.50"),
        new("badoo", "0.50"),
        new("baidu", "0.70"),
        new("bankofamerica", "0.70"),
        new("bestofourvalley", "0.70"),
        new("binance", "0.70"),
        new("bitcoinalley", "0.70"),
        new("bitflyer", "0.70"),
        new("bitmo", "0.50"),
        new("bitstamp", "0.70"),
        new("bitwage", "0.70"),
        new("blizzard", "0.50"),
        new("bluefederalcreditunion", "0.70"),
        new("bossrevolutionmoney", "0.50"),
        new("boxeddeal", "0.70"),
        new("BrandedSurvey", "0.50"),
        new("brigit", "0.50"),
        new("Bumble", "0.50"),
        new("bump", "0.70"),
        new("burner", "0.50"),
        new("capitalone", "0.70"),
        new("carepoynt", "0.70"),
        new("cashapp", "0.50"),
        new("cashshow", "0.70"),
        new("cdkeys_com", "0.70"),
        new("changelly", "0.70"),
        new("chase", "0.70"),
        new("cheapvoip", "0.70"),
        new("checkpoints", "0.70"),
        new("chime", "0.50"),
        new("cibc", "0.70"),
        new("cinchbucks", "0.70"),
        new("circle", "0.70"),
        new("cjscdkeys", "0.70"),
        new("classpass", "0.70"),
        new("clickadu", "0.70"),
        new("clickdishes", "0.70"),
        new("clover", "0.70"),
        new("coinbase", "0.50"),
        new("coingate", "0.50"),
        new("coinomi", "0.70"),
        new("coinswitch", "0.70"),
        new("cointelegraph", "0.70"),
        new("coupons", "0.50"),
        new("craigslist", "0.50"),
        new("creditkarma", "0.50"),
        new("creditsesame", "0.70"),
        new("crowdtap", "0.50"),
        new("cryptocom", "0.50"),
        new("cryptovoucher", "0.50"),
        new("current rewards", "0.50"),
        new("dabbl", "0.50"),
        new("dave", "0.50"),
        new("daybreakgames", "0.70"),
        new("dent", "0.70"),
        new("dhl", "0.70"),
        new("digit", "0.70"),
        new("discord", "0.50"),
        new("dollarclix", "0.70"),
        new("dollargeneral", "0.70"),
        new("doordash", "0.50"),
        new("dosh", "0.70"),
        new("doublelist", "0.50"),
        new("drop", "0.50"),
        new("earnably", "0.70"),
        new("earnhoney", "0.70"),
        new("earningstation", "0.50"),
        new("Ebay", "0.50"),
        new("Ebay 3", "1.00"),
        new("elepreneur", "0.70"),
        new("elevacity", "0.70"),
        new("empower", "0.70"),
        new("epicnpc", "0.70"),
        new("erewards", "0.50"),
        new("etoro", "0.50"),
        new("Eureka", "0.50"),
        new("everyoneapi", "0.70"),
        new("facebook", "0.50"),
        new("fastmail", "0.70"),
        new("fedex", "0.70"),
        new("fetchrewards", "0.50"),
        new("figureeight", "0.70"),
        new("finishline", "0.70"),
        new("fiverr", "0.50"),
        new("Flypay", "0.50"),
        new("Freecash", "0.50"),
        new("fusioncash", "0.50"),
        new("g2a", "0.50"),
        new("g2g", "0.50"),
        new("gameflip", "0.70"),
        new("gamekit", "0.70"),
        new("gemini", "0.50"),
        new("Getjerry", "0.50"),
        new("getpaidto", "0.70"),
        new("gifthulk", "0.70"),
        new("gifthunterclub", "0.70"),
        new("glidera", "0.50"),
        new("Gmail", "0.50"),
        new("Go2Bank", "0.50"),
        new("GoBank", "0.50"),
        new("GoFundMe", "0.50"),
        new("googlevoice", "1.50"),
        new("GPay", "0.50"),
        new("grabpoints", "0.50"),
        new("greendot", "0.50"),
        new("Grindr", "0.50"),
        new("groupme", "0.50"),
        new("guru", "0.70"),
        new("happn", "0.50"),
        new("harrispoll", "0.70"),
        new ("hinge", "0.50"),
        new ("homeaway", "0.70"),
        new ("hotmail", "0.50"),
        new ("hqtrivia", "0.50"),
        new ("humblebundle", "0.70"),
        new ("ibotta", "0.70"),
        new ("icq", "0.50"),
        new ("IDme", "0.50"),
        new ("imgur", "0.50"),
        new ("inboxdollars", "0.50"),
        new ("instacart", "0.50"),
        new ("instagc", "0.50"),
        new ("instagram", "0.50"),
        new ("intuit", "0.50"),
        new ("ioffer", "0.70"),
        new ("iplum", "0.50"),
        new ("ipoll", "0.50"),
        new ("irazoo", "0.70"),
        new ("juno", "0.70"),
        new ("kakaotalk", "0.50"),
        new ("kamatera", "0.70"),
        new ("keybase", "0.50"),
        new ("Klover", "0.50"),
        new ("lbryapp", "0.70"),
        new ("letgo", "0.70"),
        new ("libertyx", "0.70"),
        new ("line", "0.50"),
        new ("linkedin", "0.50"),
        new ("listia", "0.70"),
        new ("localbitcoins", "0.50"),
        new ("localcoinatm", "0.70"),
        new ("locanto", "0.70"),
        new ("lyft", "0.50"),
        new ("mailprincess", "0.70"),
        new ("mailru", "0.70"),
        new ("Marble", "0.50"),
        new ("match", "0.50"),
        new ("mercari", "0.50"),
        new ("metalpay", "0.70"),
        new ("mezu", "0.70"),
        new ("microsoftazure", "0.50"),
        new ("microsoftoffice365business", "0.50"),
        new ("microsoftoffice365e5", "0.50"),
        new ("microsoftoffice365education", "0.50"),
        new ("microsoftoutlook", "0.50"),
        new ("microsoftrewards", "0.50"),
        new ("mint", "0.70"),
        new ("mintvine", "0.70"),
        new ("mobilemoney", "0.70"),
        new ("moneylion", "0.50"),
        new ("Moneylion2", "0.50"),
        new ("mooladays", "0.70"),
        new ("moonpay", "0.50"),
        new ("movo", "0.50"),
        new ("mtcgameportal", "0.70"),
        new ("mybookie", "0.50"),
        new ("mygiftcardsupply", "0.70"),
        new ("myopinions", "0.70"),
        new ("mypoints", "0.50"),
        new ("mytrainerrewards", "0.70"),
        new ("nbatopshot", "0.50"),
        new ("nbkcbank", "0.70"),
        new ("netflix", "0.50"),
        new ("nexmo", "0.50"),
        new ("nextdoor", "0.70"),
        new ("Nielsen", "0.50"),
        new ("nike", "0.50"),
        new ("nordstrom", "0.70"),
        new ("novo", "0.70"),
        new ("offernation", "0.70"),
        new ("offerup", "0.50"),
        new ("offgamers", "0.50"),
        new ("oneopinion", "0.50"),
        new ("onlinenet", "0.70"),
        new ("OpenAI", "0.50"),
        new ("opinionsoutpost", "0.50"),
        new ("oraclecloud", "0.50"),
        new ("oxygen", "0.50"),
        new ("oyo", "0.50"),
        new ("paidviewpoint", "0.70"),
        new ("pangeamoneytransfer", "0.70"),
        new ("paxful", "0.50"),
        new ("Payactiv", "0.50"),
        new ("paybis", "0.70"),
        new ("Payoneer", "0.50"),
        new ("paypal", "0.50"),
        new ("paysend", "0.50"),
        new ("paysera", "0.70"),
        new ("pcgamesupply", "0.70"),
        new ("pei", "0.70"),
        new ("perk", "0.70"),
        new ("personalcapital", "0.70"),
        new ("playerauctions", "0.70"),
        new ("plentyoffish", "0.50"),
        new ("pncbank", "0.70"),
        new ("POF", "0.50"),
        new ("pointclub", "0.50"),
        new ("pollpass", "0.70"),
        new ("Poshmark", "0.50"),
        new ("postmates", "0.50"),
        new ("prepaid2cash", "0.70"),
        new ("Privacy", "0.50"),
        new ("prolific", "0.50"),
        new ("Propellerads", "0.70"),
        new ("propy", "0.70"),
        new ("protonmail", "0.70"),
        new ("pruvit", "0.70"),
        new ("purse_io", "0.50"),
        new ("quickthoughts", "0.50"),
        new ("radialinsight", "0.70"),
        new ("raise", "0.70"),
        new ("Remotasks", "0.50"),
        new ("retailmenot", "0.50"),
        new ("revolut", "0.50"),
        new ("rewardingways", "0.70"),
        new ("RIDLT", "0.50"),
        new ("ringcaptcha", "0.70"),
        new ("ritual", "0.50"),
        new ("savewithsurveys", "0.70"),
        new ("sayhi", "0.70"),
        new ("scaleway", "0.70"),
        new ("seagm", "0.50"),
        new ("seated", "0.50"),
        new ("Shopkick", "0.50"),
        new ("Signal", "0.50"),
        new ("Signalwire", "0.50"),
        new ("simplebank", "0.70"),
        new ("simplex", "0.50"),
        new ("skout", "0.50"),
        new ("skrill", "0.70"),
        new ("smores", "0.50"),
        new ("snagshout", "0.70"),
        new ("snapchat", "0.50"),
        new ("societi", "0.70"),
        new ("Sofi", "0.50"),
        new ("spend", "0.70"),
        new ("steam", "0.50"),
        new ("steemit", "0.70"),
        new ("Stir", "0.50"),
        new ("stripe", "0.50"),
        new ("superpay", "0.70"),
        new ("surveyhoney", "0.50"),
        new ("surveyjunkie", "0.50"),
        new ("surveymonkeyrewards", "0.70"),
        new ("surveytime", "0.50"),
        new ("swagbucks", "0.50"),
        new ("sweatcoin", "0.50"),
        new ("swych", "0.70"),
        new ("target", "0.50"),
        new ("tcgplayer", "0.70"),
        new ("tdbank", "0.70"),
        new ("telegram", "0.50"),
        new ("tencent", "0.70"),
        new ("teotaxi", "0.70"),
        new ("ticketmaster", "0.50"),
        new ("TikTok", "0.50"),
        new ("tinder", "0.50"),
        new ("Tinder 2", "0.80"),
        new ("token", "0.70"),
        new ("transferwise", "0.70"),
        new ("turo", "0.70"),
        new ("twitch", "0.50"),
        new ("twitter", "0.50"),
        new ("uber", "0.50"),
        new ("ubereats", "0.50"),
        new ("univisionmobilemoney", "0.70"),
        new ("uphold", "0.50"),
        new ("upwork", "0.50"),
        new ("usasurvey", "0.70"),
        new ("usbank", "0.70"),
        new ("valuedopinions", "0.50"),
        new ("Varo", "0.50"),
        new ("venmo", "1.00"),
        new ("vetsprevail", "0.70"),
        new ("viavan", "0.70"),
        new ("viber", "0.50"),
        new ("vk", "0.50"),
        new ("waleteros", "0.70"),
        new ("walmart", "0.50"),
        new ("walmartmoneycard", "0.50"),
        new ("walmarttfamilymobile", "0.50"),
        new ("wechat", "0.50"),
        new ("wellsfargo", "0.50"),
        new ("whatsapp", "0.60"),
        new ("whatsapp 2", "1.50"),
        new ("Whatsapp 333", "2.00"),
        new ("windowsxboxstore", "0.70"),
        new ("Womply", "0.50"),
        new ("wyre", "0.70"),
        new ("xapo", "0.70"),
        new ("xboxlive", "0.70"),
        new ("yahoo", "0.50"),
        new ("yandex", "0.70"),
        new ("yfsresearch", "0.70"),
        new ("youtube", "0.50"),
        new ("ysense", "0.50"),
        new ("yubo", "0.50"),
        new ("yunosurveys", "0.70"),
        new ("z.com", "0.50"),
        new ("zeek", "0.70"),
        new ("zelle", "0.70"),
        new ("Zogo", "0.50"),
        new ("zoho", "0.70"),
        new ("zoombucks", "0.50"),
        new ("zoosk", "0.50"),
        new ("Service not listed", "1.00"),
        new ("Other", "1.00")
    ];

    public async Task<string> GetActivationNumberAsync<T>(T app) where T : AppData
    {
        using HttpClient client = new();
        var apiUrl = $"http://codesverify.com/user/api/get_number.php?customer={ApiKey}&app={app.Name}&country=USA";
        HttpResponseMessage response = await client.GetAsync(apiUrl);
        string responseBody = await response.Content.ReadAsStringAsync();
        return responseBody;
    }

    public async Task<string> GetCodeAsync<T>(string numba, T app) where T : AppData
    {
        using HttpClient client = new();

        HttpResponseMessage response = await client.GetAsync($"http://codesverify.com/user/api/get_sms.php?customer={ApiKey}&number={numba}&country=USA&app={app.Name}");
        string responseBody = await response.Content.ReadAsStringAsync();
        return responseBody;
    }

    // Make class singleton
    private CodesVerifyAPI()
    {
    }
    private static CodesVerifyAPI instance;
    public static CodesVerifyAPI Instance
    {
        get
        {
            if (instance == null)
            {
                instance = new CodesVerifyAPI();
            }
            return instance;
        }
    }
}
