<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>Chameleon.Web.Host</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>Chameleon.Web.Host</PackageId>
    <UserSecretsId>AbpCompanyName-Chameleon-56C2EF2F-ABD6-4EFC-AAF2-2E81C34E8FB1</UserSecretsId>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <LangVersion>7.2</LangVersion>
    <Configurations>Debug;Release;Staging</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="wwwroot\swagger\ui\index.html" />
  </ItemGroup>
  <ItemGroup>
    <_WebToolingArtifacts Remove="Properties\PublishProfiles\staging.pubxml" />
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
    <None Include="wwwroot\Scripts\buyCredits.js" />
    <None Include="wwwroot\swagger\ui\abp.logs.js" />
    <None Update="Dockerfile">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Update="wwwroot\**\*">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Chameleon.Web.Core\Chameleon.Web.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Abp.Castle.Log4Net" Version="6.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="PayPalCheckoutSdk" Version="1.0.3" />
    <PackageReference Include="PayPalHttp" Version="1.0.0" />
    <PackageReference Include="Stripe.net" Version="39.48.0" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="wwwroot\swagger\ui\index.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>
    <UsingTask TaskName="TransformXml" AssemblyFile="libs\Microsoft.Web.Publishing.Tasks.dll" />
    <!--
        Please note that if IIS Express is running then Web.config is always auto updated/modified by IIS Express:
        So even if TransformXml task will run during build, then IIS Express will overwrite web.config at some point
    -->
    <Target Name="Web_config_Transform" BeforeTargets="Build" Condition="Exists('configs\Web.$(Configuration).config')">
        <!--
        <Message Text="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\Web\Microsoft.Web.Publishing.Tasks.dll" Importance="High" />
        -->
        <PropertyGroup>
            <_SourceWebConfig>$(MSBuildThisFileDirectory)configs\Web.template.config</_SourceWebConfig>
            <_XdtWebTransform>$(MSBuildThisFileDirectory)configs\Web.$(Configuration).config</_XdtWebTransform>
            <_TargetWebConfig>$(MSBuildThisFileDirectory)Web.config</_TargetWebConfig>
        </PropertyGroup>
        <Message Text="Transform $(_SourceWebConfig) with $(_XdtWebTransform) into $(_TargetWebConfig)" Importance="High" />
        <TransformXml Source="$(_SourceWebConfig)" Destination="$(_TargetWebConfig)" Transform="$(_XdtWebTransform)" />
    </Target>
    <Target Name="Log_config_Transform" BeforeTargets="Build" Condition="Exists('configs\log4net.$(Configuration).config')">
        <PropertyGroup>
            <_SourceLogConfig>$(MSBuildThisFileDirectory)configs\log4net.template.config</_SourceLogConfig>
            <_XdtLogTransform>$(MSBuildThisFileDirectory)configs\log4net.$(Configuration).config</_XdtLogTransform>
            <_TargetLogConfig>$(MSBuildThisFileDirectory)log4net.config</_TargetLogConfig>
        </PropertyGroup>
        <Message Text="Transform $(_SourceLogConfig) with $(_XdtLogTransform) into $(_TargetLogConfig)" Importance="High" />
        <TransformXml Source="$(_SourceLogConfig)" Destination="$(_TargetLogConfig)" Transform="$(_XdtLogTransform)" />
    </Target>
</Project>