<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Assets\Images\FAHeader2.png" />
	  <None Remove="Assets\Images\FAHeader2_Dark.png" />
	  <None Remove="Assets\Images\FAHeaderBackground.png" />
	  <None Remove="Assets\Images\FAHeaderBackground_Dark.png" />
	  <None Remove="Assets\Images\FAHeader_CoreControls.png" />
	  <None Remove="Assets\Images\FAHeader_CoreControls_Dark.png" />
	  <None Remove="Assets\Images\FAHeader_NewControls.png" />
	  <None Remove="Assets\Images\FAHeader_NewControls_Dark.png" />
	  <None Remove="Assets\Images\logo-long.png" />
	  <None Remove="Assets\Images\logo-merge.png" />
	  <None Remove="Assets\logo-symbol.iconset\icon_128x128.png" />
	  <None Remove="Assets\logo-symbol.iconset\icon_128x128@2x.png" />
	  <None Remove="Assets\logo-symbol.iconset\icon_16x16.png" />
	  <None Remove="Assets\logo-symbol.iconset\icon_16x16@2x.png" />
	  <None Remove="Assets\logo-symbol.iconset\icon_256x256.png" />
	  <None Remove="Assets\logo-symbol.iconset\icon_256x256@2x.png" />
	  <None Remove="Assets\logo-symbol.iconset\icon_32x32.png" />
	  <None Remove="Assets\logo-symbol.iconset\icon_32x32@2x.png" />
	  <None Remove="Assets\logo-symbol.iconset\icon_512x512.png" />
	  <None Remove="Assets\logo-symbol.iconset\icon_512x512@2x.png" />
	  <None Remove="Assets\Svgs\add.svg" />
	  <None Remove="Assets\Svgs\advanced-settings.svg" />
	  <None Remove="Assets\Svgs\arrow-down.svg" />
	  <None Remove="Assets\Svgs\arrow-left.svg" />
	  <None Remove="Assets\Svgs\arrow-right-in-circle.svg" />
	  <None Remove="Assets\Svgs\arrow-right.svg" />
	  <None Remove="Assets\Svgs\automation.svg" />
	  <None Remove="Assets\Svgs\blogger.svg" />
	  <None Remove="Assets\Svgs\bookmark-add-folder.svg" />
	  <None Remove="Assets\Svgs\brave.svg" />
	  <None Remove="Assets\Svgs\brave2.svg" />
	  <None Remove="Assets\Svgs\browsers.svg" />
	  <None Remove="Assets\Svgs\buffer-gray.svg" />
	  <None Remove="Assets\Svgs\buffer.svg" />
	  <None Remove="Assets\Svgs\bulk-plus.svg" />
	  <None Remove="Assets\Svgs\chameleon-logo.svg" />
	  <None Remove="Assets\Svgs\change-proxies.svg" />
	  <None Remove="Assets\Svgs\chrome.svg" />
	  <None Remove="Assets\Svgs\close.svg" />
	  <None Remove="Assets\Svgs\copy.svg" />
	  <None Remove="Assets\Svgs\dashboard.svg" />
	  <None Remove="Assets\Svgs\delete.svg" />
	  <None Remove="Assets\Svgs\details.svg" />
	  <None Remove="Assets\Svgs\digg.svg" />
	  <None Remove="Assets\Svgs\end-call.svg" />
	  <None Remove="Assets\Svgs\expand.svg" />
	  <None Remove="Assets\Svgs\facebook-group.svg" />
	  <None Remove="Assets\Svgs\facebook.svg" />
	  <None Remove="Assets\Svgs\firefox.svg" />
	  <None Remove="Assets\Svgs\folder.svg" />
	  <None Remove="Assets\Svgs\help.svg" />
	  <None Remove="Assets\Svgs\hide-expander.svg" />
	  <None Remove="Assets\Svgs\hootsuite.svg" />
	  <None Remove="Assets\Svgs\import-close-item.svg" />
	  <None Remove="Assets\Svgs\in-favorites.svg" />
	  <None Remove="Assets\Svgs\launch-profiles.svg" />
	  <None Remove="Assets\Svgs\line.svg" />
	  <None Remove="Assets\Svgs\linkedin.svg" />
	  <None Remove="Assets\Svgs\mailto.svg" />
	  <None Remove="Assets\Svgs\minus-in-circle.svg" />
	  <None Remove="Assets\Svgs\new-folder.svg" />
	  <None Remove="Assets\Svgs\next.svg" />
	  <None Remove="Assets\Svgs\no-address.svg" />
	  <None Remove="Assets\Svgs\no-business.svg" />
	  <None Remove="Assets\Svgs\no-logins.svg" />
	  <None Remove="Assets\Svgs\no-peresons.svg" />
	  <None Remove="Assets\Svgs\not-favorites.svg" />
	  <None Remove="Assets\Svgs\not-profiles.svg" />
	  <None Remove="Assets\Svgs\outreach-no-saved-links.svg" />
	  <None Remove="Assets\Svgs\phone-chat.svg" />
	  <None Remove="Assets\Svgs\phone-verification.svg" />
	  <None Remove="Assets\Svgs\pins-gray.svg" />
	  <None Remove="Assets\Svgs\pins.svg" />
	  <None Remove="Assets\Svgs\plus-in-circle.svg" />
	  <None Remove="Assets\Svgs\plus.svg" />
	  <None Remove="Assets\Svgs\prev.svg" />
	  <None Remove="Assets\Svgs\profile-addresses.svg" />
	  <None Remove="Assets\Svgs\profile-businesses.svg" />
	  <None Remove="Assets\Svgs\profile-logins.svg" />
	  <None Remove="Assets\Svgs\profile-main.svg" />
	  <None Remove="Assets\Svgs\profile-persons.svg" />
	  <None Remove="Assets\Svgs\profiles.svg" />
	  <None Remove="Assets\Svgs\prospector.svg" />
	  <None Remove="Assets\Svgs\purchase.svg" />
	  <None Remove="Assets\Svgs\re-do.svg" />
	  <None Remove="Assets\Svgs\re-name.svg" />
	  <None Remove="Assets\Svgs\reddit-gray.svg" />
	  <None Remove="Assets\Svgs\reddit.svg" />
	  <None Remove="Assets\Svgs\refresh.svg" />
	  <None Remove="Assets\Svgs\release-number.svg" />
	  <None Remove="Assets\Svgs\reminder.svg" />
	  <None Remove="Assets\Svgs\rss.svg" />
	  <None Remove="Assets\Svgs\save.svg" />
	  <None Remove="Assets\Svgs\saved-links.svg" />
	  <None Remove="Assets\Svgs\scoop-it.svg" />
	  <None Remove="Assets\Svgs\search.svg" />
	  <None Remove="Assets\Svgs\select-all.svg" />
	  <None Remove="Assets\Svgs\selected-folder.svg" />
	  <None Remove="Assets\Svgs\settings.svg" />
	  <None Remove="Assets\Svgs\shares.svg" />
	  <None Remove="Assets\Svgs\sharing-purple.svg" />
	  <None Remove="Assets\Svgs\sharing.svg" />
	  <None Remove="Assets\Svgs\shavron-list.svg" />
	  <None Remove="Assets\Svgs\shavron.svg" />
	  <None Remove="Assets\Svgs\show-expander.svg" />
	  <None Remove="Assets\Svgs\socials.svg" />
	  <None Remove="Assets\Svgs\start-youtube-uploading.svg" />
	  <None Remove="Assets\Svgs\subredits.svg" />
	  <None Remove="Assets\Svgs\SumSymbol.svg" />
	  <None Remove="Assets\Svgs\support.svg" />
	  <None Remove="Assets\Svgs\sync.svg" />
	  <None Remove="Assets\Svgs\synch.svg" />
	  <None Remove="Assets\Svgs\text-search.svg" />
	  <None Remove="Assets\Svgs\three-dots.svg" />
	  <None Remove="Assets\Svgs\triangle-for-button.svg" />
	  <None Remove="Assets\Svgs\tumblr.svg" />
	  <None Remove="Assets\Svgs\twitter.svg" />
	  <None Remove="Assets\Svgs\undo.svg" />
	  <None Remove="Assets\Svgs\up-folder.svg" />
	  <None Remove="Assets\Svgs\Vector.svg" />
	  <None Remove="Assets\Svgs\website.svg" />
	  <None Remove="Assets\Svgs\wordpress.svg" />
	  <None Remove="Assets\Svgs\wrench.svg" />
	  <None Remove="Assets\Svgs\x.svg" />
	  <None Remove="Assets\Svgs\youtube.svg" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Assets\Addons\ClientRectsAddon\data\popup\popup.css" />
	  <Content Include="Assets\Addons\ClientRectsAddon\data\popup\popup.html" />
	  <Content Include="Assets\Addons\FontDefenderAddon\data\popup\explore\explore.css" />
	  <Content Include="Assets\Addons\FontDefenderAddon\data\popup\explore\explore.json" />
	  <Content Include="Assets\Addons\FontDefenderAddon\data\popup\popup.css" />
	  <Content Include="Assets\Addons\FontDefenderAddon\data\popup\popup.html" />
	  <Content Include="Assets\Addons\FontDefenderAddon\manifest.json" />
	  <Content Include="Assets\Addons\GeoAddonv2\data\editor\index.css" />
	  <Content Include="Assets\Addons\GeoAddonv2\data\editor\index.html" />
	  <Content Include="Assets\Addons\GeoAddonv2\data\icons\bypassed\16.png" />
	  <Content Include="Assets\Addons\GeoAddonv2\data\icons\bypassed\32.png" />
	  <Content Include="Assets\Addons\GeoAddonv2\data\icons\bypassed\48.png" />
	  <Content Include="Assets\Addons\GeoAddonv2\data\icons\denied\16.png" />
	  <Content Include="Assets\Addons\GeoAddonv2\data\icons\denied\32.png" />
	  <Content Include="Assets\Addons\GeoAddonv2\data\icons\denied\48.png" />
	  <Content Include="Assets\Addons\GeoAddonv2\data\icons\granted\16.png" />
	  <Content Include="Assets\Addons\GeoAddonv2\data\icons\granted\32.png" />
	  <Content Include="Assets\Addons\GeoAddonv2\data\icons\granted\48.png" />
	  <Content Include="Assets\Addons\GeoAddonv3\data\editor\index.css" />
	  <Content Include="Assets\Addons\GeoAddonv3\data\editor\index.html" />
	  <Content Include="Assets\Addons\GeoAddonv3\data\icons\bypassed\16.png" />
	  <Content Include="Assets\Addons\GeoAddonv3\data\icons\bypassed\32.png" />
	  <Content Include="Assets\Addons\GeoAddonv3\data\icons\bypassed\48.png" />
	  <Content Include="Assets\Addons\GeoAddonv3\data\icons\denied\16.png" />
	  <Content Include="Assets\Addons\GeoAddonv3\data\icons\denied\32.png" />
	  <Content Include="Assets\Addons\GeoAddonv3\data\icons\denied\48.png" />
	  <Content Include="Assets\Addons\GeoAddonv3\data\icons\granted\16.png" />
	  <Content Include="Assets\Addons\GeoAddonv3\data\icons\granted\32.png" />
	  <Content Include="Assets\Addons\GeoAddonv3\data\icons\granted\48.png" />
	  <Content Include="Assets\Addons\TimezoneAddonv2\data\icons\updating\16.png" />
	  <Content Include="Assets\Addons\TimezoneAddonv2\data\icons\updating\32.png" />
	  <Content Include="Assets\Addons\TimezoneAddonv2\data\icons\updating\512.png" />
	  <Content Include="Assets\Addons\TimezoneAddonv2\data\options\index.css" />
	  <Content Include="Assets\Addons\TimezoneAddonv2\data\options\index.html" />
	  <Content Include="Assets\Addons\TimezoneAddonv2\manifest.json" />
	  <Content Include="Assets\Addons\TimezoneAddonv3\data\icons\updating\16.png" />
	  <Content Include="Assets\Addons\TimezoneAddonv3\data\icons\updating\32.png" />
	  <Content Include="Assets\Addons\TimezoneAddonv3\data\icons\updating\512.png" />
	  <Content Include="Assets\Addons\TimezoneAddonv3\data\options\index.css" />
	  <Content Include="Assets\Addons\TimezoneAddonv3\data\options\index.html" />
	  <Content Include="Assets\Addons\TimezoneAddonv3\manifest.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\data\icons\disabled\16.png" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\data\icons\disabled\32.png" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\data\icons\disabled\48.png" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\data\icons\disabled\512.png" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\data\icons\red\16.png" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\data\icons\red\32.png" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\data\icons\red\48.png" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\data\icons\red\512.png" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\data\options\index.css" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\data\options\index.html" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\manifest.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\ar\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\bg\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\cs\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\de\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\el\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\en\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\es\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\fr\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\he\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\hi\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\hu\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\id\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\it\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\ja\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\ko\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\nl\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\no\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\pl\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\pt_BR\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\pt_PT\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\ro\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\ru\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\sv\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\tr\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\uk\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\zh_CN\messages.json" />
	  <Content Include="Assets\Addons\WebRtcAddonv3\_locales\zh_TW\messages.json" />
	  <Content Include="Assets\Fonts\Nunito\Nunito-Italic-VariableFont_wght.ttf" />
	  <Content Include="Assets\Fonts\Nunito\Nunito-VariableFont_wght.ttf" />
	  <Content Include="Assets\Fonts\Nunito\OFL.txt" />
	  <Content Include="Assets\Fonts\Nunito\README.txt" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-Black.ttf" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-BlackItalic.ttf" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-Bold.ttf" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-BoldItalic.ttf" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-ExtraBold.ttf" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-ExtraBoldItalic.ttf" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-ExtraLight.ttf" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-ExtraLightItalic.ttf" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-Italic.ttf" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-Light.ttf" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-LightItalic.ttf" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-Medium.ttf" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-MediumItalic.ttf" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-Regular.ttf" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-SemiBold.ttf" />
	  <Content Include="Assets\Fonts\Nunito\static\Nunito-SemiBoldItalic.ttf" />
	</ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Svg.Skia" />
    <PackageReference Include="Avalonia.Xaml.Behaviors" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Chameleon.Common\Chameleon.Common.csproj" />
    <ProjectReference Include="..\..\..\src\Chameleon.Interfaces\Chameleon.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controls\" />
    <Folder Include="Converters\ValueConverters\Visibility\" />
    <Folder Include="Util/" />
  </ItemGroup>

</Project>
