<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Assets\Images\FAHeader2.png" />
	  <None Remove="Assets\Images\FAHeader2_Dark.png" />
	  <None Remove="Assets\Images\FAHeaderBackground.png" />
	  <None Remove="Assets\Images\FAHeaderBackground_Dark.png" />
	  <None Remove="Assets\Images\FAHeader_CoreControls.png" />
	  <None Remove="Assets\Images\FAHeader_CoreControls_Dark.png" />
	  <None Remove="Assets\Images\FAHeader_NewControls.png" />
	  <None Remove="Assets\Images\FAHeader_NewControls_Dark.png" />
	</ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Chameleon.Interfaces\Chameleon.Interfaces.csproj" />
    <ProjectReference Include="..\Chameleon.Avalonia.Prism.Interfaces\Chameleon.Avalonia.Prism.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controls\" />
  </ItemGroup>

</Project>
