<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Newtonsoft.Json" />
	<PackageReference Include="Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\chameleon-lib\Chameleon.lib.ThirdParty\Chameleon.lib.ThirdParty.csproj" />
    <ProjectReference Include="..\..\Chameleon.CommunityToolkit\Chameleon.CT.Common\Chameleon.CT.Common.csproj" />
    <ProjectReference Include="..\Chameleon.Common\Chameleon.Common.csproj" />
    <ProjectReference Include="..\Chameleon.Core\Chameleon.Core.csproj" />
    <ProjectReference Include="..\Chameleon.Interfaces\Chameleon.Interfaces.csproj" />
  </ItemGroup>

   <ItemGroup>
     <AvaloniaResource Include="Addons\ChameleonAddon.cs" />
   </ItemGroup>

   <ItemGroup>
     <Folder Include="Manager\" />
   </ItemGroup>

</Project>
